name: CI
on:
  # 自动触发条件（push 或 PR）
  push:
  pull_request:
  # 添加手动触发选项
  workflow_dispatch:
    inputs:
      branch:
        description: "Alpine 分支（默认测试矩阵中的 latest-stable 和 edge）"
        required: false
        default: "matrix"
      extra_packages:
        description: "额外安装的包（覆盖 --packages 参数）"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["latest-stable", "edge"]
    # 如果手动触发时指定了分支，则覆盖矩阵中的分支
    steps:
      - uses: actions/checkout@v4

      - name: Determine branch to use
        id: set-branch
        run: |
          if [ "${{ github.event_name == 'workflow_dispatch' && inputs.branch != 'matrix' }}" = "true" ]; then
            echo "Using manually specified branch: ${{ github.event.inputs.branch }}"
            echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "Using matrix branch: ${{ matrix.branch }}"
            echo "branch=${{ matrix.branch }}" >> $GITHUB_OUTPUT
          fi

      - name: Build rootfs tarball
        run: |
          sudo ./alpine-make-rootfs \
              --branch "${{ steps.set-branch.outputs.branch }}" \
              --packages "${{ github.event.inputs.extra_packages || 'ruby sqlite' }}" \
              --script-chroot \
              example-$(date +%Y%m%d).tar.gz -- ./example/install.sh

      - name: Build rootfs from stdin
        run: |
          cd example
          sudo ../alpine-make-rootfs \
              --branch "${{ steps.set-branch.outputs.branch }}" \
              --packages "${{ github.event.inputs.extra_packages || 'ruby sqlite' }}" \
              --script-chroot \
              rootfs - < install.sh
